---

    - name: Install load balancer packages
      package:
        name: "{{ load_balancer_packages }}"
        state: present
    
    - name: Configure haproxy load balancing
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: start haproxy
    
    - name: Enable Haproxy
      service:
        name: "{{payload}}"
        enabled: true