---
- name: Install tomcat
  yum:
    name: "{{ payload }}"
    state: present

- name: Enable tomcat start at boot
  systemd:
    name: tomcat
    enabled: yes

- name: Create MyApp path
  file:
    path: /usr/share/tomcat/webapps/MyApp
    state: directory
    owner: root
    group: tomcat

- name: Copy html into tomcat apps folder
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/MyApp/index.html
    owner: root
    group: tomcat
  

- name: Edit tomcat file to include MyApp by default
  blockinfile:
    path: "/etc/tomcat/server.xml"
    state: present
    insertbefore: "</Hosts>"
    block: |
      <Context path="" docBase="MyApp">
        <!-- Default set of monitored resources -->
      <WatchedResource>WEB-INF/web.xml</WatchedResource>
      </Context>
  notify: start {{ payload }}  
