---
- name: Install tomcat
  yum:
    name: "{{ payload }}"
    state: present

- name: Enable tomcat start at boot
  service:
    name: tomcat
    enabled: yes

- name: Create MyApp folder
  file:
    path: /usr/share/tomcat/webapps/MyApp
    state: directory
    owner: root
    group: tomcat

- name: Copy html file into tomcat apps folder
  template:
    src: index.html.j2
    dest: /usr/share/tomcat/webapps/MyApp/index.html
    owner: root
    group: tomcat
    mode: 0644
  
- name: Copy server.xml to avoid typing /MyApp on url
  template:
    src: server.xml.j2
    dest: /etc/tomcat/server.xml
    owner: root
    group: tomcat
  notify: start {{ payload }}  